[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_KEY = ""
  NEXT_PUBLIC_USERNAME = ""
  NEXT_PUBLIC_PASSWORD = ""

[[plugins]]
  package = "@netlify/plugin-nextjs" 