[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_USERNAME = "XcmEgUAyLCYCwLWrjANhTPk"
  NEXT_PUBLIC_PASSWORD = "QpCwZdvhihbTcGKZaMxfxWomyHE"
  NEXT_PUBLIC_API_KEY = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJHcm91cE5hbWUiOiJOZXd0b24gQ29tbXVuaXR5IiwiVXNlck5hbWUiOiJOZXd0b24gQ29tbXVuaXR5IiwiQWNjb3VudCI6IiIsIlN1YmplY3RJRCI6IjE5MDk2NDk4MDQ4OTIzMTE4MjkiLCJQaG9uZSI6IiIsIkdyb3VwSUQiOiIxOTA5NjQ5ODA0ODgzOTIzMjIxIiwiUGFnZU5hbWUiOiIiLCJNYWlsIjoic2FmZW5ld3RvbmNvbW11bml0eUBnbWFpbC5jb20iLCJDcmVhdGVUaW1lIjoiMjAyNS0wNC0wOSAwMzozMjo1OSIsIlRva2VuVHlwZSI6MSwiaXNzIjoibWluaW1heCJ9.dQ3HfqdGj2Bm_0r1RHUqOL6h5BCqdxJf-8yPGgIdvz6gI8H3Vd4BnpgP5jTaEQADUMEYPEgrvF1cLFzWdg09HVU7Vr0-A-oIu0D1OQgESnebATNPxONlTybDWFcSwCI7ierC7BYUniVQf-VQDT3FeADk5a_2Es8i5mNRSId_hS1HinDWz1fEjPf1Mk3BWP6LvTSgqSKTjGns7tETSruAlKfh4uM9CPdNSCx3q2TIyNGJhWhHHzZ_XVN9ddUzbcOUb3CssKtH8G-JNjMA5Gcn4wa9tO9rqTlLgpAQnYlPqs1mOWNyb7DDam2IfY_s018j6lPspR795bbWk1_IGK4YYA"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.processing]
  skip_processing = true 