[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_USERNAME = "test"
  NEXT_PUBLIC_PASSWORD = "test"
  NEXT_PUBLIC_API_KEY = "your_api_key_here"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.processing]
  skip_processing = true 